---

- include: fix_etc_hosts.yml

- name: Add clearwater apt key
  apt_key: url=http://repo.cw-ngv.com/repo_key state=present

- name: Add clearwater apt repository
  apt_repository: repo='deb http://repo.cw-ngv.com/stable binary/' state=present

- name: Install clearwater auto config
  apt: name=clearwater-auto-config-generic force=yes

- name: Configure clearwater
  template: src=clearwater_config.j2 dest=/etc/clearwater/config