---
  - name: download package
    get_url: 'url="{{ package_url }}" dest="/var/tmp" use_proxy="{{ use_proxy }}"'
    register: temp_file

  - name: create install directory
    command: mkdir -pm 755 '{{ install_dir }}'

  - name: extract package
    command: tar xf '{{ temp_file.dest }}' chdir='{{ install_dir }}'

  - name: set executable
    command: chmod '{{ executable }}' chdir='{{ install_dir }}'

  - name: cleanup
    command: rm '{{ temp_file.dest }}'
