---
- name: Install clearwater in a box
  hosts: clearwater_single

  roles:
    - common
    - ellis
    - bono 
    - restund
    - sprout
    - homer
    - homestead

  tasks:
    - include: roles/common/tasks/create_numbers.yml